# Training data has 100M tokens...
# # base — ~8M params
name: base
config:
  block_size: 2000       # 10 second long 
  window_size: 500       # 2.5 second long 
  input_dim: 508 # 
  n_layer: 4
  n_head: 6
  n_embd: 384
  dropout: 0.15
  bias: False 