diffusion: edm
model:
  image_size: 32          # MNIST padded to 32x32
  in_channels: 1          # grayscale
  out_channels: 1         # grayscale
  model_channels: 64      # smaller number of channels
  attention_resolutions:   # optional, can even remove if you want
  - 8
  num_res_blocks: 1       # fewer residual blocks
  channel_mult:
  - 1
  - 2
  num_heads: 4            # fewer attention heads
  resblock_updown: false   # not needed for small images


trainer:
  constructor_args:
    lr: 1.e-3
    output_dir: /scratch/gilbreth/ahmedb/trained_models/mnist
    exp_name: mnist_generation
    distributed: False

  train_args:
    batch_size: 128
    batch_size_per_device: 128
    max_steps: 10000
    num_epochs: null
    chkpt_save_steps: 2000  
    train_log_steps: 1000 
    eval_log_steps: 2000 
    resume_training: False

